### ISSUE TITLE
No devices showing

### ISSUE THREAD

**Issue by Katamave** [FreshlyBrewedCode/hacs-homee#22] opened 2022-12-02 13:14 UTC
Hi,

i dont  know why but my config window is empty.

Configure the homee integration. You may need to restart Home Assistant to apply the changes.

The groups that should be imported
Groups that contain window sensors
Groups that contain door sensors

this is all is get. I have only one entity and that is homee it self.
I have 4 Garage doors from Hörmann. But somehow they dont show up in the integration config.
![homee](https://user-images.githubusercontent.com/1660199/205300810-bd46b4ff-7d4c-4b1a-b142-7944f03d31d9.png)

**Comment by FreshlyBrewedCode** [comment] 2022-12-02 14:51
Can you check the HA logs to see if there are any errors related to the integration?

**Comment by Katamave** [comment] 2022-12-07 09:16
Hi, sorry for a late reply.
I couldn't find anything in HA logs. Integration setups without any error.
Maybe its Homee it self? This is a Homee cube from Hörmann it self.

**Comment by FreshlyBrewedCode** [comment] 2022-12-07 17:51
It is strange that no groups show up in the configuration screen. Whether or not the garage doors you mentioned are supported by the integration I don't know. Unfortunately, I can't really do any testing because I don't have a working homee setup anymore.

**Comment by deel77** [comment] 2022-12-15 22:01
@Katamave I have just installed whole Homee and until I added garage doors to groups inside Homee this integration wasn't able to pick it. Try creating new group in Homee app and then reload it in HA. It showed for me. But cannot open/close garage doors it only shows current status :(

**Comment by Katamave** [comment] 2022-12-15 22:54
> @Katamave I have just installed whole Homee and until I added garage doors to groups inside Homee this integration wasn't able to pick it. Try creating new group in Homee app and then reload it in HA. It showed for me. But cannot open/close garage doors it only shows current status :(

Worked for me too! But cant open/close like you :(

**Comment by FreshlyBrewedCode** [comment] 2022-12-16 09:56
Devices can only be added if there are in a group. That is intended behavior although it is annoying if you just want to import everything (there is already an issue regarding this: #5). I'm closing this since the devices not showing up should be resolved by using groups in homee.
Regarding the garage doors, it might be that the specific model is simply not supported by the integration. You can open a separate issue if you want, however, as I said I am only passively maintaining this repo and won't work on any new features or major fixes.

**Closed by FreshlyBrewedCode** 2022-12-16 09:56 UTC
Labels: bug
